krishastore/skilltriks

- .github/deployment/scripts/production-deployment.sh
**Code Quality**
**Performance**
**Security**
**Other**
**Reviewers, please make sure to address the following:**
> Update production deployment path in script

- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/Feature_request.yml
- .github/dependabot.yml
- .github/labeler.yml
- .github/workflows/build-dev-artifacts.yml
- .github/workflows/test-php.yml
**Code Quality**
**Performance**
**Security**
**Other**
**Reviewers, please make sure to address the following:**
> Restore old ci-cd files

- readme.txt
- skilltriks.php
- src/Helpers/SettingOptions.php
- templates/admin/course/course-settings.php
- templates/admin/quiz/metabox-quiz-settings.php
- templates/admin/settings/setting-theme.php
- Hide add on tabs for plugin release
- Removed extra tabs as they were not planned in development :- https://3.basecamp.com/3122880/buckets/35653575/card_tables/cards/8499240571
> Hide add on tabs for plugin release

- assets/js/src/assigncourse.js
- assets/js/src/frontend.js
- assets/scss/assigncourse.scss
- assets/scss/frontend/_button.scss
- assets/scss/frontend/_course-detail.scss
- assets/scss/frontend/_course-item.scss
- assets/scss/frontend/_form.scss
- assets/scss/frontend/_variable.scss
- assets/scss/frontend/assign-course.scss
- assets/scss/frontend/course-list.scss
- assets/scss/frontend/notification.scss
- assets/scss/frontend/style.scss
- package-lock.json
- package.json
- src/Admin/Core.php
- src/Helpers/Utility.php
- src/Shortcode/AssignCourse.php
- src/Shortcode/AssignNewCourse.php
- src/Shortcode/AssignedCourse.php
- src/Shortcode/Register.php
- templates/admin/users/capability-edit.php
- templates/frontend/assign-course-by-me.php
- templates/frontend/assign-course-to-me.php
- templates/frontend/assign-new-course.php
- templates/frontend/sub-header.php
- tests/test-user-role.php
- webpack.config.js
> Feat: assign course

- assets/js/src/assigncourse.js
Closes: https://github.com/krishastore/skilltriks/issues/246
> Fixed update completion date

- templates/frontend/assign-course-by-me.php
- templates/frontend/assign-course-to-me.php
Closes: https://github.com/krishastore/skilltriks/issues/240
> Add dash when completion date is empty

- templates/frontend/assign-course-by-me.php
Closes: https://github.com/krishastore/skilltriks/issues/242
> Fixed remove edit button

- src/Collections/PostTypes.php
- templates/frontend/assign-course-by-me.php
Fixes: https://github.com/krishastore/skilltriks/issues/251, https://github.com/krishastore/skilltriks/issues/241, https://github.com/krishastore/skilltriks/issues/247
> Fixed assign course table

- templates/frontend/courses.php
Fixes: https://github.com/krishastore/skilltriks/issues/239
> Fixed hide category level

- assets/scss/assigncourse.scss
> Fix: increase line height for label

- .github/deployment/scripts/dev-deployment.sh
- .github/deployment/scripts/production-deployment.sh
- .github/workflows/dev-deployment.yml
- Added dev deployment yml file
- Added dev deployment sh file
- Added secrets variables
> Add dev deployment files

- src/Shortcode/AssignCourse.php
- src/Shortcode/AssignNewCourse.php
- templates/frontend/assign-course-to-me.php
Fixes: https://github.com/krishastore/skilltriks/issues/270
> Fix: duplicate assigner name in dropdown

- assets/scss/assigncourse.scss
> Fix: improve toast message structure

- src/Shortcode/AssignNewCourse.php
Fixes: https://github.com/krishastore/skilltriks/issues/275
> Fixed show new course on top

- assets/js/src/frontend.js
- readme.txt
- skilltriks.php
- templates/frontend/assign-course-by-me.php
- templates/frontend/assign-course-to-me.php
- templates/frontend/courses.php
- templates/frontend/mylearning.php
Fixes: https://github.com/krishastore/skilltriks/issues/277
> Fixed filter toggle on mobile view

- readme.txt
- skilltriks.php
- Updated Plugin Version
- Update Changelog
> Update plugin version and changelog

- README.md
- readme.txt
Add user manual link in readme file
> Add user manual

- src/Helpers/SettingOptions.php
Remove extra " <<<<<<< development " text
> Resolve merge conflict

- src/Helpers/Notification.php
- src/Helpers/Utility.php
- src/Notification/DueCourseNotification.php
- src/Notification/DueSoonCourseNotification.php
- src/Notification/OverDueCourseNotification.php
- src/Shortcode/AssignCourse.php
- src/Shortcode/AssignNewCourse.php
- src/Shortcode/Notification.php
- src/constants.php
- src/helpers.php
- templates/frontend/course-result.php
- templates/frontend/notifications.php
- templates/frontend/sub-header.php
- Convert the static notification page to dynamic
- Add notification table 
- Retrieve data using the transient for better performance
> Feat: notification log

- src/Helpers/Utility.php
- src/Shortcode/Notification.php
- templates/frontend/notifications.php
- Created a daily cron function to cleanup notification older than 180 days
> Notification cleanup

- src/helpers.php
- Fixes: https://github.com/krishastore/skilltriks/issues/313
> Fixed highlight lesson name in notification

- assets/js/src/course.js
Fixes : https://github.com/krishastore/skilltriks/issues/325
> Fixed sorting issue in course curriculum sections

- assets/js/src/userprofile.js
- assets/scss/userprofile.scss
- src/Helpers/Utility.php
- src/Shortcode/Courses.php
- src/Shortcode/UserProfile.php
- templates/frontend/userprofile.php
Fixes :- 
- https://github.com/krishastore/skilltriks/issues/327
- https://github.com/krishastore/skilltriks/issues/328
- https://github.com/krishastore/skilltriks/issues/329
- https://github.com/krishastore/skilltriks/issues/331
- https://github.com/krishastore/skilltriks/issues/332
- https://github.com/krishastore/skilltriks/issues/333
- https://github.com/krishastore/skilltriks/issues/334
> Fixed minor bugs in profile page
